### ISSUE TITLE
Bild kann auf mobilen Geräten nicht angezeigt werden (Direkte Speicherung auf dem Server) 

### ISSUE THREAD

**Issue by CitySim** [CitySim/NSA-Stundenplan#10]
dann brauchen wir aber einen File Upload auf den Server
ist so deutlich einfacher

**Comment by CitySim** [comment]
http://www.mkyong.com/webservices/jax-rs/file-upload-example-in-jersey/

**Comment by leonard-** [comment]
Lösung: URL mit Bild auf dem Server damit man es ohne Internet sehen kann.
